### ISSUE TITLE
ApkTrack often does not download APKs

### ISSUE THREAD

**Issue by Olf0** [JusticeRage/ApkTrack#108] opened 2017-09-01 00:07 UTC
ApkTrack does not download apks from other sources than f-droid (have not tested Gplay though): 
When hitting the "downward arrow to bar" (no matter if it is flashing or not; I have yet to comprehend what a flashing arrow indicates, in contrast to a static one) either nothing happens at all, or a download is initiated, but ends with displaying an empty notification and then nothing happens. 

When performing the same actions with an app, which has f-droid selected as source, everything works fine: After the downloading a proper notification is shown and a symbol is displayed (instead of the arrow), with which the installation can be triggered. 

Tested with ApkTrack 2.1.1 (and mostly ApkTrack Proxy as source) under AOSP 4.1.2

Please let me know, if logs etc. would be helpful.

**Comment by JusticeRage** [comment] 2017-09-01 14:52
There is currently an issue with the ApkTrack proxy, where the major website queried to download APKs (APKMirror) has started using cloud-flare and is rate-limiting requests. I'm currently looking into it.

**Comment by Olf0** [comment] 2017-09-01 22:33
Thanks for your explanation and for planning to take a closer look at this issue.

**Comment by JusticeRage** [comment] 2017-09-04 11:11
I am currently discussing with APKMirror's admin regarding accessing their API, so hopefully this will be resolved soon.

**Comment by Olf0** [comment] 2017-09-16 22:19
I will investigate this further with ApkTrack 2.1.2 (or later), when having sufficient time to do that thoroughly.

**Comment by JusticeRage** [comment] 2017-10-31 14:12
I am now in a position to provide more info on this issue. The proxy is running on a VPS with limited resources and APKs are cached for 24h to avoid drawing too much bandwidth from scrapped websites (especially APKMirror).
I'm not sure how big ApkTrack's user base actually is, but I realized that the 20 GB of disk space I had were being filled constantly. This caused a lot of downloads to fail on the server's side, which in turn resulted in failed downloads in the app all over the world. I have purchased a VPS with more capacity (50 GB) which seems to have solved this problem entirely from what I can see. 

I'll leave you to confirm and close the issue if the problem doesn't manifest itself anymore on your end either.

**Comment by Olf0** [comment] 2017-11-02 02:00
Will check and either close this or report.

**Comment by Olf0** [comment] 2017-12-16 23:33
A few tests worked well, hence I am closing this issue.

Still I wonder, as already mentioned in [the last two paragraphs of my comment in issue #112](https://github.com/JusticeRage/ApkTrack/issues/112#issuecomment-347634296), why (just quoting the last sentence here):
> As the ApkTrack Proxy consumes quite some bandwidth and storage space (for which you pay), I also wonder why the XML data of these sources [which offer their repository data in a well defined format] is not directly parsed by ApkTrack (hence moving the workload from the ApkTrack Proxy to the clients running ApkTrack)?

**Closed as completed** 2017-12-16 23:34 UTC

**Comment by JusticeRage** [comment] 2017-12-18 13:50
Great!
As for your question, I don't pay for the bandwidth, only the storage space. It's a bit easier to process XML (and generally, complex page data) on the server, because if the target website is modified, I don't have to push an update to all the users to correct the parsing. All I need to do is update the proxy code and the problem is fixed immediately for all users.

**Comment by Olf0** [comment] 2017-12-18 16:10
> It's a bit easier to process XML (and generally, complex page data) on the server, because if the target website is modified, [...]

This confuses me.
If you parse the well defined repository XML data in the ApkTrack client (as you do for e.g. the I2P F-Droid repository), it does not matter if a website is altered.  This is exactly the point about those well defined XML formats: They are rarely altered, and if so the version string at the beginning of a XML file must be increased, so it is easily detectable.
In contrast to that "webpage scraping" breaks easily and often, as those webpages are regularly altered and there is no easy way of automatically detecting this, as are just made for being read by humans, not machines.

**Comment by JusticeRage** [comment] 2017-12-18 20:19
The XML formats do change from time to time. And some of them can be parsed easily, others (Guardian Project) contain relative URLs that require processing.
It's true that XML formats are mostly more stable than random web pages.
