### ISSUE TITLE
Problem with the size of the icons

### ISSUE THREAD

**Issue by xavihernandez** [JusticeRage/ApkTrack#76] opened 2015-11-19 13:35 UTC
Hi thanks for this useful tool @JusticeRage :)

"Redetect installed applications" entry has disappeard from menu. Then application says some applications are not up-to-date while they are. But aplication still got old version number.

Before I was able to tap on "Redetect installed applications" to refresh them.

**Comment by DJaeger** [comment] 2015-11-19 14:53
The new version doesn't need it anymore.
Please uninstall and install ApkTrack again.
It could be, that it has merged that wrong data on update.

**Comment by xavihernandez** [comment] 2015-11-19 15:13
@DJaeger  OK I'll do. I have deleted data already. But I'm gonna uninstall/install again ;)
Thanks.

**Comment by xavihernandez** [comment] 2015-11-19 15:18
@DJaeger oh also, why is there big icons and normal sized icons in applications list ? It looks weird

**Comment by DJaeger** [comment] 2015-11-19 17:44
Is it now working like expected?

The icons are delivered by Android with different dimensions.
You are right, looks weird.
Would you create a new issue for it, with a description and a screenshot?

**Comment by xavihernandez** [comment] 2015-11-19 17:53
I'll let you know when I install a new version of an app ;).

Ok I'll (this evening or tomorrow) no problem.
Thanks for your help

**Comment by DJaeger** [comment] 2015-11-19 19:10
Great

**Comment by JusticeRage** [comment] 2015-11-19 21:52
Hi!
The "large icons" problem was reported to me on XDA, and I have been working on it during the past few days. The general idea is that ApkTrack does some icon resizing to make sure that no picture breaks the layout - but in order to determine the right size, some special handling was done depending on the screen's density.
It turned out that while the most common screen densities were handled, some devices used different ones, and in that case, ApkTrack made the conservative choice of not resizing icons (because it wasn't clear which size should be used). In any case, the icon size is now calculated from the screen's DPI, and should work on any device.
If you would like to help, you are welcome to try out [this APK](http://apktrack.kwiatkowski.fr/apk/ApkTrack-xavi.apk). Let me know if it solved the icon problem for you.

The refreshing installed apps issue interests me the most. I had removed the "refresh installed apps" button in version 2.0.0 because I felt that it was bad interface, and also because I had done some work to make sure that ApkTrack doesn't miss any app update / installation anymore.
I would love to hear more about how to reproduce the problem.

**Comment by xavihernandez** [comment] 2015-11-20 10:27
@JusticeRage this version fixes weird icon size :)
I won't open a new issue then.

About installed apps, it seems that your version fixes the issue (or maybe it has been fixd by reinstalling before istalling your version I cannot say). 

Thanks !

**Comment by DJaeger** [comment] 2015-11-20 17:52
The icon issue is still not solved completly.
It's still wrong at the icon of QKSMS.

**Comment by JusticeRage** [comment] 2015-11-20 17:56
I was really hoping that problem was solved :(
What is the issue (oversized or too small)? What is your screen's DPI? A screenshot might help as well.

**Comment by JusticeRage** [comment] 2015-11-22 15:55
A user has submitted a patch to solve this issue without having to do any manual resizing.
Let me know if you still see the issue with this [new APK](http://apktrack.kwiatkowski.fr/apk/ApkTrack-DJaeger.apk)!

**Comment by DJaeger** [comment] 2015-11-22 19:39
Yes, this is working for all my apps.

**Closed as completed** 2015-11-22 19:46 UTC

**Comment by xavihernandez** [comment] 2015-11-23 09:50
As far as I"m concerned, it was ok for QKSMS on previous version too.

**Comment by JusticeRage** [comment] 2015-11-23 09:57
You and @DJaeger probably have devices with a different screen density.

**Comment by xavihernandez** [comment] 2015-11-23 10:05
Yep 420 here with a Samsung Galxy Note 3 (non standard density)

**Comment by xavihernandez** [comment] 2015-11-23 15:10
@JusticeRage @DJaeger Applications still not auto update in list. For instance I have updated UnifiedNlpProvider from 0.1.6 to 0.1.8 and ApkTrack still showing that 0.1.6 is installed and tells me I have to update. Same for WorldWeather, etc.

**Comment by JusticeRage** [comment] 2015-11-23 15:23
That's a bug. Would you be able to reproduce the issue and send me the logcat output (let me know if you need instructions for that last part)?

**Comment by xavihernandez** [comment] 2015-11-23 15:43
I'll. It's easy to reproduce, I have just to tap on an application, and it says that it is outdated, while I have last version.

Nothing interesting written in logcat :

Sugar        InstalledApp saved : 3
AkpTrack   LaunchingVersioncheck for org.openmap.unifiedNlp
ApkTrack   Obtained version 0.1.8 - Download URL : https://f-droid.org/repo/or.openmap.unifiedNlp_9.apk
Sugar        InstalledApp saved : 3

**Comment by JusticeRage** [comment] 2015-11-23 15:46
Would you be able to post a screenshot?

**Comment by xavihernandez** [comment] 2015-11-23 15:55
Here you go :

![screenshot_2015-11-23-16-52-16](https://cloud.githubusercontent.com/assets/3322064/11341449/d0c187ba-9202-11e5-9ab5-971764747230.png)
![screenshot_2015-11-23-16-52-52](https://cloud.githubusercontent.com/assets/3322064/11341465/d9e87ca4-9202-11e5-8256-4d99f93097a8.png)

**Comment by JusticeRage** [comment] 2015-11-23 16:03
Great, thank you for this.
I know it's a bother, but would you be able to re-install the 0.1.8 unifiedNlpProvider APK and send me logcat output? I would like to see if ApkTrack misses the Intent which is fired on an upgrade, or if the Intent is received but handled incorrectly.

**Comment by xavihernandez** [comment] 2015-11-23 16:22
No problem, just give me few minutes, finishing something before :)

**Comment by xavihernandez** [comment] 2015-11-23 17:18
Deleting and reinstalling seems to have fired INTENT.
**V/ApkTrack( 7155): Received APP_REMOVED (org.openbmap.unifiedNlp). The activity will be informed.** 
As we can see : 
**V/ApkTrack( 7155): Received APP_ADDED (org.openbmap.unifiedNlp). The activity will be informed.**

While it seems that an UPDATE to a package is a PACKAGE_REMOVED and PACKAGE_ADDED INTENTS combo, I think we should have the same behavior, but Shazam has not been updated in ApkTrack, and INTENT has not been handled.

[apktrack_logcat.txt](https://github.com/JusticeRage/ApkTrack/files/41828/apktrack_logcat.txt)

**Comment by JusticeRage** [comment] 2015-11-23 17:18
Quick question: I noticed both programs come from F-Droid. Did you install them by manually downloading an APK or through the F-Droid app? I don't know how they perform the upgrades but it might be the cause.

**Comment by xavihernandez** [comment] 2015-11-23 17:21
Through F-Droid, but, Aplication Manager is launched, it is not automatically installed by F-Droid. It's kinda like a F-Droid download + manual install (it's juste that install windows is launched by F-Droid and not by my tap action on an apk file), rather than an installation BY F-Droid.

**Comment by JusticeRage** [comment] 2015-11-23 17:23
Okay. That's probably not it then.
Thanks for the Logcat, I'll look into it!

EDIT: The missed intent issue has been traced to ApkTrack beeing frozen by Greenify. A note has been added to the changelog in case someone else encounters this problem.
