### ISSUE TITLE
Option for choose preferred update source

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#41] opened 2015-04-18 14:20 UTC
I want to choose F-Droid as defauls update source.
The most apps on my phone are from F-Droid, but a lot of them are also available in Google Play.
Currently I have to choose F-Droid manually for every App that is available in Google Play.
I want to set it one time in the options, so that it always be used as preferred choose, for currently installed and also new apps.

**Comment by JusticeRage** [comment] 2015-04-20 13:52
This is indeed a desirable feature.
Right now, when no update source is defined, sources are tried in the order of the [sources.json](https://github.com/JusticeRage/ApkTrack/blob/master/assets/sources.json) file. Since the file is modified a lot, it made sense to separate it from the code, and allowing any permutation of the sources in the settings would create some dependencies I'm not comfortable with (i.e. "Try the third source first, then the rest in the order of the list" is dangerous since there is no guarantee that the third source will remain the same over time - the list may go down to two items for all I know.).

I want to implement this, but it may not be trivial.

**Comment by DJaeger** [comment] 2015-04-21 15:22
I think a first possible solution could be to reorder the json.
I think the common usecase of this solution is if one haven't gapps on his phone and prefer F-Droid.
So reorder Play to the bottom and F-Droid to the top.

**Comment by JusticeRage** [comment] 2015-04-21 21:32
That makes sense, but I would still like to offer some kind of choice through the settings.
The default should probably be "F-Droid first" indeed.

**Comment by DJaeger** [comment] 2015-04-21 22:06
It was only an workaround proposal if the real sollution would take to much time to be ready soon.

**Comment by JusticeRage** [comment] 2015-04-22 03:23
Preliminary tests show that pushing F-Droid to the top may cause issues with some applications which F-Droid masks (see #24: Google Play Services, for instance, is shadowed by a F-Droid app and defaulting to F-Droid for everyone results in a wrong version number.)
Some apps are also simply outdated (i.e. [TalkBack](https://f-droid.org/repository/browse/?fdfilter=talkback&fdid=com.google.android.marvin.talkback) 3.2.1 instead of 4.1.0.
Because of this, sadly, F-Droid may not be a safe default selection.

**Comment by DJaeger** [comment] 2015-04-22 12:22
For the apps I have tested it with it works with the APK you have supplied in #39

**Comment by JusticeRage** [comment] 2015-04-22 12:26
Oh, the "try F-Droid first" part works. The problem is that F-Droid is not a suitable update source for some common applications, such as Google Play Services. I'm afraid using it by default will create some confusion for other users who won't understand why GPS's latest version is 1.3.x instead of 7.x :(

I think the only option here is to allow a modification of the update source ordering in the settings.

**Comment by DJaeger** [comment] 2015-04-22 14:18
I think mainly the system apps in googles namespace are a problem.
And for these apps the only trustful source will be the Google Play Store.
You could say, that these apps are limited to this single source, like the only allow ApkTrack source for ApkTrack, but with an wildcard, for example com.google.*

**Comment by JusticeRage** [comment] 2015-04-22 14:42
This may work. I could restrict F-Droid to all apps that don't start with `com.google`. 
µG UnifiedNlp wouldn't work with F-Droid anymore, but if it's a only for a couple of apps, I guess  I can have a workaround in the code.

**Comment by DJaeger** [comment] 2015-04-22 17:21
If I'm right you need for UnifiedNlp the modul from Xposed and also the UnifiedNlp App from F-Droid.

You should restrict com.google.android.\* and com.android.*
as there are multiple common apps in com.google namspace.
For example Google Code Projects and the ZXing Barcodescanner.

The only exceptions I get for com.google.android are:
com.google.android.apps.athenticator2
com.google.android.diskusage
com.google.android.stardroid
com.google.android.gms
com.google.android.location
and outdated (latest FLOSS-Version?):
com.google.android.marvin.talkback

And the exceptions I get for com.android are:
com.android.camera2
com.android.keepass
com.android.launcher3
com.android.music
com.android.quake
com.android.shellms

Or this to much to make exception, as there also could come more?

**Comment by DJaeger** [comment] 2015-08-19 07:11
To determine the source of the app and with that the store to check, the CN or Organisation of the apk signature could be used.
F-Droid: `O=fdroid.org`
GuardianProject: `O=Guardian Project` or `O=guardianproject.info`

Xposed Installer: `CN=rovo89`
Öffi: `CN=Andreas Schildbach`

Do not check for example a CN of "Buildozer" as this are developer builds.

**Comment by JusticeRage** [comment] 2015-08-19 09:37
That's a great idea. I'll implement this right away.

**Comment by JusticeRage** [comment] 2015-11-10 22:00
Fixed in version 2.0 (93e4e93bd1c48cb6ec1db40efc144eaafbf61276).

**Closed as completed by JusticeRage** 2015-11-10 22:00 UTC
