### ISSUE TITLE
Add option to ignore app

### ISSUE THREAD

**Issue by Mosrite** [JusticeRage/ApkTrack#25] opened 2015-03-16 11:17 UTC
Could you please add an option to ignore (or even hide) certain apps?
I mostly use F-Droid to download apps. However, I am aware that F-Droid updates are usually a bit behind the official latest release. So, I don't need be informed about updates for apps I got from F-Droid.
Thanks for considering my suggestion!

**Comment by JusticeRage** [comment] 2015-03-16 12:14
Hi ! The ability to check for updates from F-Droid is currently under work, so it may be one solution for your problem when it's done.
Hiding apps would be something interesting to do, but I'll have to figure out a nice way to un-hide them afterwards. Let's discuss this again when #4 is fixed!

**Comment by JusticeRage** [comment] 2015-03-23 16:37
Hey! I have published a new [Beta APK](http://kwiatkowski.fr/apktrack/ApkTrack_beta.apk) which adds the option to track updates from F-Droid. Let me know if this is an acceptable solution to the problem for you!

**Comment by Mosrite** [comment] 2015-03-23 16:42
The link seems to be broken.

**Comment by JusticeRage** [comment] 2015-03-23 16:53
Forgot the "http" part, sorry about that.

**Comment by Mosrite** [comment] 2015-03-23 17:26
That should work, yes! Thanks! :)

**Comment by Mosrite** [comment] 2015-03-23 17:54
Apparently, the app doesn't save the settings. It still checks all sources and change settings automatically, if it finds a newer version from a different source.

**Comment by JusticeRage** [comment] 2015-03-23 18:04
This is not what I intended. Normally, ApkTrack shouldn't look for updates beyond the user-specified source.
Do you have a particular example of the problem? What are the steps to take to reproduce it?

**Comment by Mosrite** [comment] 2015-03-24 10:34
You can reproduce this with every app of which a newer version is available on the Play Store than on F-Droid.

**Comment by JusticeRage** [comment] 2015-03-24 16:07
That's the thing, it works for me - that's why I need more specific information.
For instance, if I take Google Play Services (com.google.android.gms): selecting Appbrain gives me the right version. But then if I select "F-Droid", I get [a package](https://f-droid.org/repository/browse/?fdfilter=com.google.android.gms&fdid=com.google.android.gms) with the same name but a different version number (1.3.0). The version returned does match the selected source every time I try.

I'm not denying that I made a mistake in my implementation, but I would need a little more help to narrow down where the problem is.

For instance, it would be a great help if you could tell me how the bug is triggered for you. Which app is used? Which update source have you selected? Do you perform a manual update check (by clicking the app), or do you wait until the background service triggers one?
What do you do after

**Comment by Mosrite** [comment] 2015-03-25 14:58
This happens for every app: If I select F-Droid, then manually check for new updates and Google Play has a more recent update, then Google Play is automatically selected as default source. Also, if I select Google Play but the app cannot be found there, then my default selection is deleted.

**Comment by JusticeRage** [comment] 2015-03-25 16:40
I have uploaded an [APK](http://kwiatkowski.fr/apktrack/ApkTrack_Mosrite.apk) with additional logging. It probably won't fix your problem, but I hope it will help me debug it.
Could you try installing it, reporting any errors and posting the logcat after trying to update from F-Droid?

Thank you!

**Comment by Mosrite** [comment] 2015-03-25 18:17
Don't ask me why, but it worked now.
But I figured an option to ignore apps would still be nice. This is because some apps might be sideloaded as apk or from additional F-Droid repositories (e.g. Guardian Project) that your app cannot check.

**Comment by JusticeRage** [comment] 2015-03-25 18:20
Great to see that one of the problems has been fixed.
I'll keep the "hinding apps" problem in mind. As stated before, it has to come along with a solution to unhide apps and I'm not sure how to present this yet.

That being said, if there are other repositories you would like ApkTrack to check, feel free to open a new issue!

**Comment by Mosrite** [comment] 2015-03-25 21:52
You could just add an additional list accessible in the settings that contains all ignored apps. From there the user could un-ignore an app again.

**Comment by DJaeger** [comment] 2015-04-18 14:24
Something like the list tabs for example within F-Droid

**Comment by DJaeger** [comment] 2015-06-09 08:01
If it is not required to realy hide an app but to simply not check for version (which should be the case for APKs installed manually) it should be enought to simply add an dummy source that does nothing , that you can chosen from source menu.

**Comment by JusticeRage** [comment] 2015-11-10 22:02
Fixed in version 2.0 (93e4e93bd1c48cb6ec1db40efc144eaafbf61276).

**Closed as completed by JusticeRage** 2015-11-10 22:02 UTC
